      REAL*8 FUNCTION GET_LARGEST_REMNANT(M_TAR, M_PRO, R_TAR, R_PRO, B, L_LAP, MIU_ALPHA, QR)
C      IMPLICIT NONE
      INCLUDE 'COMMONP.FOR'
      REAL*8  RHO1, CSTAR, MIU_AVE, GAMMA, MTOT, M_SUN, RC1_M, RC1, MIU, QRD, QRD1, QRD2
      REAL*8  M_TAR, M_PRO, R_TAR, R_PRO, B, L_LAP, MIU_ALPHA, QR

C     DENSITY IN KG/M^3
      RHO1 = 1000
      CSTAR = 5
      MIU_AVE = 0.37
C
      GAMMA = M_PRO/M_TAR
      MTOT = M_TAR + M_PRO
C     RC1 IN M UNIT
      M_SUN = 1.989E30
      RC1_M = (MTOT*M_SUN/((4/3)*3.14*RHO1))**0.333
C     RC1 IN AU UNIT
      RC1 = RC1_M/1.5E11
C
      MIU = M_TAR*M_PRO/MTOT
C
      QRD = CSTAR*(3.0/5)*MTOT/RC1
      QRD1 = QRD*((GAMMA+1)**2/(4*GAMMA))**(2/(3*MIU_AVE)-1)
      IF (NC.GT.0) THEN
         QRD2 = QRD1
      ELSE 
         QRD2 = (MIU/MIU_ALPHA)**(2-3*MIU_AVE/2)*QRD1
      END IF
C
      IF(0.LT.QR/QRD2.AND.QR/QRD2.LT.1.8) GET_LARGEST_REMNANT = MTOT*((1- QR/QRD2)*0.5 + 0.5)
      IF (QR/QRD2.GE.1.8) GET_LARGEST_REMNANT = MTOT*0.1*(QRD2/QR)**(1.5)*1.8**1.5
C
      RETURN
      END

